config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}
  
  resources :students   
  resources :lessons

  root "main_page#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  
  belongs_to :student

  validates :date, presence: true 
  validates :duration, presence: true 
  validates :location, presence: true 

end

app/models/pay.rb
class Pay < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :lessons, dependent: :destroy
	
	validates :name, presence: true 
	validates :subject, presence: true 
	validates :location, presence: true 
	validates :pay_by_hour, presence: true 



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :array_student, only: [:new , :edit]

  def index
    @lessons = Lesson.order(:date)
  end

  def show
  end

  def new
    @lesson = Lesson.new
    
  end

  def create
      @lesson = Lesson.new lesson_params    
      if @lesson.save
        flash[:success] = "Новый урок добавлен"
        redirect_to lessons_path
      else
        render :new
      end
  end

  def edit
    @lesson = Lesson.find params[:id]
  end

  def update
    @lesson = Lesson.find params[:id]

      if @lesson.update(lesson_params)
        flash[:success] = "Урок обновлен"
        redirect_to lessons_path
      else
        render :edit
      end
  end

  def destroy
    @lesson = Lesson.find params[:id]
      if @lesson.delete
        flash[:success] = "Урок удален"
        redirect_to lessons_path , status: 303
      else
        render :index
      end
  end


  private
    def lesson_params
      params.require(:lesson).permit(:student_id, :date, :duration, :location, :subject) 
    end
    def array_student
      @array_student = Student.all.map { |student| [student.name , student.id]}
    end
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private
	def after_sign_up_path_for(resource)
	  root_path
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def show
  end

  def new
    @student = Student.new
  end

  def create
      @student = Student.new student_params     
      if @student.save
        flash[:success] = "Новый ученик добавлен"
        redirect_to students_path
      else
        render :new
      end
  end

  def edit
    @student = Student.find params[:id]
  end

  def update
    @student = Student.find params[:id]
    if @student.update student_params
      flash[:success] = "Данные изменены"
      redirect_to students_path
    else
      render :edit
    end
  end

  def destroy
    @student = Student.find params[:id]
    if @student.destroy
      flash[:success] = "Ученик удален"
      redirect_to students_path , status: 303
    else
      render :edit
    end
  end

  private
  def student_params
    params.require(:student).permit(:name, :subject, :location, :pay_by_hour, :other, :class_in_school, :phone_number) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRMForRepetitors</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>



  </head>

  <%= render "shared/navbar" %>

  <body>
<!--      <%= render "shared/devise_flash" %> -->

    <%=render "shared/flash" %>
    <%= yield %>
   
</html>

app/views/lessons/edit.html.erb
<div class="m-2 p-2">

	
	<div class="m-2 p-2 border border-2  shadow-lg">
	<h3 class="m-2 p-2 px-3 py-3 border border-2 rounded  shadow-lg fw-light">Добавить урок</h3>
		<%= form_with model: @lesson do |form| %>
			<div class="input-group flex-nowrap m-2 w-75 ">
				<%= form.label "Ученик", class:"input-group-text" %>
			 	<%= form.select :student_id, @array_student, options = {}, class:"form-select"  %>
			</div>
			<div class="input-group flex-nowrap m-2 w-75 ">
				<%= form.label "Дата и время", class:"input-group-text " %>		
				<%= form.datetime_select :date , {}, {class:"form-select"} %>
			</div>
			<div class="input-group flex-nowrap m-2 w-75 ">
				<%= form.label "Продолжительность" , class:"input-group-text" %>
			 	<%= form.select :duration, [60,90,120], options = {}, class:"form-select"  %>
 			</div>
 			<div class="input-group flex-nowrap m-2 w-75">
				<%= form.label "Место", class:"input-group-text" %>
			 	<%= form.select :location, ["Дом", "Онлайн", "Выезд"], options = {}, class:"form-select"  %>

				<%= form.label "Предмет", class:"input-group-text" %>
				<%= form.select :subject, ["Математика","Физика","Математика + Физика"], options = {}, class:"form-select" %>
			</div>

			<div class="input-group flex-nowrap m-2 mt-3 "> 
				<%= form.submit  "OK" , class:"input-group-text p-2" %>
				
			</div>
			
			
		<% end %>

	</div>
</div>

app/views/lessons/index.html.erb
<div class="m-2 p-2 border border-2  shadow-lg">
	<h3 class="m-2 p-2">Список всех уроков</h2>
	<% @lessons.each do |lesson| %>

	<div class="m-2 p-3 border border-2  shadow-lg">
		<p><%= lesson.date %> </p>
		<h4> <%= lesson.student.name %> </h4>
		<p><%= lesson.subject %> </p>

	    <%= link_to "Подробнее", lesson_path(lesson.id), class:"input-group-text btn btn-sm btn-dark" %>
	    <%= link_to "Изменить", edit_lesson_path(lesson.id), class:"input-group-text btn btn-sm btn-dark" %>
    	<%= link_to "Удалить", lesson_path(lesson.id), data: {"turbo-method": :delete, "turbo-confirm":"Вы точно хотите удалить данный урок?" }, class:"input-group-text btn btn-sm btn-dark" %>
	</div>

	<% end %>
</div>

app/views/lessons/new.html.erb
<div class="m-2 p-2">

	
	<div class="m-2 p-2 border border-2  shadow-lg">
	<h3 class="m-2 p-2 px-3 py-3 border border-2 rounded  shadow-lg fw-light">Добавить урок</h3>
		<%= form_with model: @lesson do |form| %>
			<div class="input-group flex-nowrap m-2 w-75 ">
				<%= form.label "Ученик", class:"input-group-text" %>
			 	<%= form.select :student_id, @array_student, options = {}, class:"form-select"  %>
			</div>
			<div class="input-group flex-nowrap m-2 w-75 ">
				<%= form.label "Дата и время", class:"input-group-text " %>		
				<%= form.datetime_select :date , {}, {class:"form-select"} %>
			</div>
			<div class="input-group flex-nowrap m-2 w-75 ">
				<%= form.label "Продолжительность" , class:"input-group-text" %>
			 	<%= form.select :duration, [60,90,120], options = {}, class:"form-select"  %>
 			</div>
 			<div class="input-group flex-nowrap m-2 w-75">
				<%= form.label "Место", class:"input-group-text" %>
			 	<%= form.select :location, ["Дом", "Онлайн", "Выезд"], options = {}, class:"form-select"  %>

				<%= form.label "Предмет", class:"input-group-text" %>
				<%= form.select :subject, ["Математика","Физика","Математика + Физика"], options = {}, class:"form-select" %>
			</div>

			<div class="input-group flex-nowrap m-2 mt-3 "> 
				<%= form.submit  "OK" , class:"input-group-text p-2" %>
				
			</div>
			
			
		<% end %>

	</div>
</div>

app/views/lessons/show.html.erb
<h1>Lessons#show</h1>
<p>Find me in app/views/lessons/show.html.erb</p>

app/views/main_page/index.html.erb
<div class="m-2 p-2">
	<h1 >Это CRM для репетиторов</h1>
	<p>Здесь можно вести список учеников, строить расписание контролировать оплату</p>

</div>

app/views/shared/_devise_flash.html.erb
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

app/views/shared/_flash.html.erb
    
      <% flash.each do |k, v| %>
        <%= tag.div v, class: "alert alert-#{k}", role: 'alert' %>
      <% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">Домашня страница</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Ученики
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<%= students_path %>">Список всех учеников</a></li>
            <li><a class="dropdown-item" href="<%= new_student_path %>">Добавить нового ученика</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Уроки
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="<%= lessons_path %>">Список всех уроков</a></li>
            <li><a class="dropdown-item" href="<%= new_lesson_path %>">Создать новый урок</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Расписание</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <% if signed_in? %>
        <li>   <%= link_to "Выйти", destroy_user_session_path, data: {"turbo-method": :delete, "turbo-confirm":"Вы точно хотите выйти?" }, class:"input-group-text btn btn-outline-danger" %></li>
      <% else %>
        <li><%= link_to "Войти",new_user_session_path, class:"navbar-brand" %></li>
        <li><%= link_to "Зарегестрироваться",new_user_registration_path, class:"navbar-brand"  %></li>
     <% end %>
    </div>
  </div>
</nav>

app/views/students/_form_for_new_edit.html.erb
<div class="m-2 p-2">

	
	<div class="m-2 p-2 border border-2  shadow-lg">
	<h3 class="m-2 p-2 px-3 py-3 border border-2 rounded  shadow-lg fw-light">Добавить нового ученика</h3>
		<%= form_with model: @student do |form| %>
			<div class="input-group flex-nowrap m-2 w-75 ">
				<%= form.label "Имя" , class:"input-group-text" %>
				<%= form.text_field :name, class:"form-control " ,placeholder:"Имя" , required: true, minlength:3%>
			</div>
			<div class="input-group flex-nowrap m-2 w-75">
				<%= form.label "Предмет", class:"input-group-text" %>
				<%= form.select :subject, ["Математика","Физика","Математика + Физика"], options = {}, class:"form-select" %>

				<%= form.label "Класс" , class:"input-group-text" %>
			 	<%= form.select :class_in_school, (7..11).to_a, options = {}, class:"form-select"  %>
			</div>
 			<div class="input-group flex-nowrap m-2 w-75">
				<%= form.label "Место", class:"input-group-text" %>
			 	<%= form.select :location, ["Дом", "Онлайн", "Выезд"], options = {}, class:"form-select"  %>

				<%= form.label "Оплата в час", class:"input-group-text" %>
			 	<%= form.select :pay_by_hour, [700,800, 900,1000,1100], options = {}, class:"form-select"  %>
			</div>
			<div class="input-group flex-nowrap m-2 w-75"> 
				<%= form.label "Номер телефона",class:"input-group-text" %>
				<%= form.text_field :phone_number , class:"form-control" ,placeholder:"+7......"%>	
			</div>
			<div class="input-group flex-nowrap m-2 w-75"> 
				<%= form.label "Дополнительная информация",class:"input-group-text" %>
				<%= form.text_field :other , class:"form-control" ,placeholder:"Дополнительная информация"%>	
			</div>
			<div class="input-group flex-nowrap m-2 mt-3 "> 
				<%= form.submit  button_name , class:"input-group-text p-2" %>
			</div>
			
			
		<% end %>
	</div>
</div>

app/views/students/edit.html.erb
<%= render "form_for_new_edit", button_name: "Изменить" %>

app/views/students/index.html.erb
<div class="m-2 p-2">
	<h2 >Список всех учеников</h2>
</div>

<% @students.each do |student| %>
 <div class="m-2 p-2 border border-2">
 	<div > 	 
 	 <h3 class = "input-group-text w-25"> <%= student.name %> </h3>
 	</div>
	 <a class="input-group-text btn btn-outline-dark" data-bs-toggle="collapse" href="#student-<%=student.id%>" role="button" aria-expanded="false" aria-controls="collapseExample"> Подробнее </a>

 	<div class="collapse" id="student-<%=student.id%>">
		 <div class="card card-body">
		 	 <p> Предмет: <%= student.subject %></p>
		 	 <p> Класс в школе: <%= student.class_in_school %> </p>
		 	 <p> Место проведения: <%= student.location %></p>
		 	 <p> Оплата за час: <%= student.pay_by_hour %></p>
		 	 <p> Номер телефона: <%= student.phone_number %></p>
		 	 <p> Дополнительная информация: <%= student.other %></p>
		</div>
    </div>
    <%= link_to "Изменить", edit_student_path(student.id), class:"input-group-text btn btn-outline-secondary" %>
    <%= link_to "Удалить", student_path(student.id), data: {"turbo-method": :delete, "turbo-confirm":"Вы точно хотите удалить данного ученика??" }, class:"input-group-text btn btn-outline-danger" %>
 </div>





</div>


 <% end %>

app/views/students/new.html.erb
<%= render "form_for_new_edit", button_name: "Добавить" %>

app/views/students/show.html.erb
<h1>Students#show</h1>
<p>Find me in app/views/students/show.html.erb</p>